GET http://{{host}}:{{port}}/{{context}}/rest/admin?year=1&date=2020-01-01
Accept: application/json

###
POST http://{{host}}:{{port}}/{{context}}/rest/admin/staffDetail
Content-Type: application/json

{
  "staffId": "cs103",
  "staffName": "sathish",
  "dob": "1998-02-12",
  "password": "staff@test",
  "mailId": "sathish@gmail.com",
  "address": "thiruvallur",
  "mobileNumber": "0987654331"
}

###
POST http://{{host}}:{{port}}/{{context}}/rest/admin/staffDetailView
Content-Type: application/json

{}

###
POST http://{{host}}:{{port}}/{{context}}/rest/admin/studentDetailView
Content-Type: application/json

{}

###
POST http://{{host}}:{{port}}/{{context}}/rest/admin/studentDetail
Content-Type: application/json

{
  "registerNumber": "110816104120",
  "studentName": "kanru",
  "department": "cse",
  "mailId": "karan@gmail.com",
  "address": "chennai",
  "mobileNumber": "1234567897",
  "dob": "2020-02-20",
  "year": "3"
}

###
