POST http://{{host}}:{{port}}/{{context}}/rest/saveAttendanceRecord
Content-Type: application/json

{
  "registerNumber": "110816104111",
  "date": "2020-01-15",
  "inTime": "10:01:00",
  "coordinateStaff": "bharathimohan",
  "description": "test-1 ",
  "year": "1"
}

###
