POST http://localhost:8081/lms/rest/uploadStudentRecord
Content-Type: application/json

{
  "registerNumber": "110816104037",
  "date": "2020-01-06",
  "time": "10:10:00",
  "staffName": "bharathimohan",
  "description": "test-1 "
}

###
